# Test configuration for data generation

logging:
  log_dir: logs/test_data_generation # Separate log directory for test runs
  level: INFO # Use INFO or DEBUG for testing

data_generation:
  num_samples: 4 # Generate a small number of samples for testing
  output_dir: data/test_run/processed # Base output directory for the test run
  resolutions: # Define the single resolution for this test
    - [32, 32]
  domain_size_x: 5000.0 # Physical domain size X (adjust if needed)
  domain_size_y: 5000.0 # Physical domain size Y (adjust if needed)

  parameter_type: spatial # Generate spatial parameters for U and K_f

  # Simulation parameters (will be adapted for the specified resolution)
  simulation_params:
    # grid_shape: Will be set based on 'resolutions' list above
    # grid_length: Will be set based on domain_size_x/y above
    time_step: 1000.0 # Simulation time step
    run_time: 20000.0 # Total simulation time
    boundary_status: 'fixed_value' # Boundary conditions

  # Parameter ranges for SCALAR sampling (used as base, overridden by spatial if active)
  parameter_ranges:
    uplift__rate: [5e-4, 1.5e-3] # Base range if not spatial
    spl__k_coef: [2e-6, 8e-6]   # Base range if not spatial
    diffusion__diffusivity: [0.2, 0.8] # Diffusivity remains scalar
    spl__area_exp: [0.45, 0.55]      # m exponent (scalar)
    spl__slope_exp: 1.0              # n exponent (fixed scalar)

  # Configuration for SPATIAL parameters (only used if parameter_type is 'spatial')
  spatial_parameter_config:
    uplift__rate:
      pattern: 'fault' # Generate a fault pattern for uplift
      min: 5e-4        # Value on one side of the fault
      max: 1.5e-3      # Value on the other side
    spl__k_coef:
      pattern: 'random' # Generate a random field for erodibility
      min: 2e-6
      max: 8e-6